"""baseline

Revision ID: 6ea9b46b7a65
Revises: 
Create Date: 2026-08-10 23:44:24.964467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea9b46b7a65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_contacts')
    op.drop_table('laborantin')
    op.drop_table('role_permissions')
    op.drop_table('psych_evaluations')
    op.drop_table('secretaire')
    op.drop_table('audit_logs')
    op.drop_table('spiritual_attendance')
    op.drop_index(op.f('idx_admissions_active'), table_name='admissions', postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.drop_table('admissions')
    op.drop_table('doctor')
    op.drop_table('spiritual_sessions')
    op.drop_table('motif_translations')
    op.drop_table('permissions')
    op.drop_table('audit_access_old')
    op.drop_table('nurse')
    op.drop_table('lab_results_audit')
    op.drop_table('admin')
    op.drop_table('audit_user_actions_old')
    op.drop_index(op.f('idx_appointments_date'), table_name='appointments')
    op.create_unique_constraint(None, 'appointments', ['uuid'])
    op.create_index(op.f('ix_audit_access_access_id'), 'audit_access', ['access_id'], unique=False)
    op.create_index(op.f('ix_audit_user_actions_action_id'), 'audit_user_actions', ['action_id'], unique=False)
    op.drop_index(op.f('idx_caisse_payment_method'), table_name='caisse')
    op.drop_index(op.f('idx_caisse_status'), table_name='caisse')
    op.drop_constraint(op.f('caisse_item_transaction_fkey'), 'caisse_item', type_='foreignkey')
    op.create_foreign_key(None, 'caisse_item', 'caisse', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_caisse_retrait_category'), table_name='caisse_retrait')
    op.alter_column('consultation_spirituel', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultation_spirituel', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultation_spirituel', 'created_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('consultation_spirituel', 'presc_generic',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=20)),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'presc_med_spirituel',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=10)),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'mp_type',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'psaume',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('consultation_spirituel_mp_type_fkey'), 'consultation_spirituel', type_='foreignkey')
    op.create_foreign_key(None, 'consultation_spirituel', 'prayer_book_type', ['mp_type'], ['type_code'])
    op.alter_column('lab_result_details', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_lab_details_parametre'), table_name='lab_result_details')
    op.drop_constraint(op.f('lab_result_details_parametre_id_fkey'), 'lab_result_details', type_='foreignkey')
    op.drop_constraint(op.f('lab_result_details_result_id_fkey'), 'lab_result_details', type_='foreignkey')
    op.create_foreign_key(None, 'lab_result_details', 'parametres', ['parametre_id'], ['id'])
    op.create_foreign_key(None, 'lab_result_details', 'lab_results', ['result_id'], ['result_id'])
    op.alter_column('lab_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('lab_results', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('lab_results', 'external_patient_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('lab_results', 'batch_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifiant unique de lot (UUID) pour grouper les examens créés simultanément',
               existing_nullable=True)
    op.drop_index(op.f('idx_code_lab_patient'), table_name='lab_results')
    op.drop_index(op.f('idx_lab_result_code'), table_name='lab_results')
    op.drop_index(op.f('idx_lab_results_batch_id'), table_name='lab_results')
    op.drop_index(op.f('idx_lab_results_patient_date'), table_name='lab_results')
    op.create_index(op.f('ix_lab_results_batch_id'), 'lab_results', ['batch_id'], unique=False)
    op.create_unique_constraint(None, 'lab_results', ['code_lab_patient'])
    op.drop_table_comment(
        'lab_results',
        existing_comment='Résultats de laboratoire liés aux dossiers médicaux',
        schema=None
    )
    op.drop_index(op.f('idx_medical_records_motif_code'), table_name='medical_records')
    op.drop_index(op.f('idx_medical_records_patient_date'), table_name='medical_records')
    op.create_unique_constraint(None, 'medical_records', ['uuid'])
    op.create_index(op.f('ix_organization_config_id'), 'organization_config', ['id'], unique=False)
    op.drop_index(op.f('idx_paiement_trans_id'), table_name='paiement_echelonne')
    op.drop_constraint(op.f('fk_paiement_caisse'), 'paiement_echelonne', type_='foreignkey')
    op.create_foreign_key(None, 'paiement_echelonne', 'users', ['handled_by'], ['user_id'])
    op.create_foreign_key(None, 'paiement_echelonne', 'caisse', ['transaction_id'], ['transaction_id'])
    op.alter_column('parametres', 'input_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'numeric'::character varying"))
    op.drop_index(op.f('idx_parametres_examen'), table_name='parametres')
    op.drop_constraint(op.f('parametres_examen_id_fkey'), 'parametres', type_='foreignkey')
    op.create_foreign_key(None, 'parametres', 'examens', ['examen_id'], ['id'])
    op.drop_index(op.f('idx_patients_active'), table_name='patients', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_patients_clinical'), table_name='patients', postgresql_where='(is_clinical = true)')
    op.drop_index(op.f('idx_patients_code_search'), table_name='patients')
    op.drop_index(op.f('idx_patients_full_name_lower'), table_name='patients')
    op.drop_index(op.f('idx_patients_global_search'), table_name='patients', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_patients_name_rev_search'), table_name='patients')
    op.drop_index(op.f('idx_patients_spiritual'), table_name='patients', postgresql_where='(is_spiritual = true)')
    op.drop_index(op.f('idx_patients_toxico'), table_name='patients', postgresql_where='(is_toxicology = true)')
    op.create_unique_constraint(None, 'patients', ['uuid'])
    op.drop_index(op.f('idx_pharmacy_drug_name_lower'), table_name='pharmacy')
    op.drop_index(op.f('idx_pharmacy_stock_status'), table_name='pharmacy')
    op.alter_column('prescriptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_index(op.f('idx_prescriptions_patient_status'), table_name='prescriptions')
    op.create_unique_constraint(None, 'prescriptions', ['uuid'])
    op.create_foreign_key(None, 'prescriptions', 'medical_records', ['medical_record_id'], ['record_id'])
    op.drop_table_comment(
        'prescriptions',
        existing_comment='Prescriptions médicales liées aux dossiers médicaux',
        schema=None
    )
    op.alter_column('reference_ranges', 'sexe',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_index(op.f('idx_reference_ranges_parametre'), table_name='reference_ranges')
    op.drop_constraint(op.f('reference_ranges_parametre_id_fkey'), 'reference_ranges', type_='foreignkey')
    op.create_foreign_key(None, 'reference_ranges', 'parametres', ['parametre_id'], ['id'])
    op.alter_column('toxico_dossiers', 'relapse_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('toxico_dossiers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_toxico_active'), table_name='toxico_dossiers', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_toxico_psy'), table_name='toxico_dossiers')
    op.drop_constraint(op.f('fk_toxico_patient'), 'toxico_dossiers', type_='foreignkey')
    op.drop_constraint(op.f('fk_toxico_psychologist'), 'toxico_dossiers', type_='foreignkey')
    op.create_foreign_key(None, 'toxico_dossiers', 'users', ['psychologist_id'], ['user_id'])
    op.create_foreign_key(None, 'toxico_dossiers', 'patients', ['patient_id'], ['patient_id'])
    op.alter_column('toxico_evaluations', 'phase_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('toxico_evaluations', 'phase_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_eval_creator'), 'toxico_evaluations', type_='foreignkey')
    op.drop_constraint(op.f('fk_eval_dossier'), 'toxico_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'toxico_evaluations', 'toxico_dossiers', ['dossier_id'], ['id'])
    op.create_foreign_key(None, 'toxico_evaluations', 'users', ['created_by'], ['user_id'])
    op.alter_column('toxico_phase_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'En cours'::character varying"))
    op.drop_constraint(op.f('fk_history_dossier'), 'toxico_phase_history', type_='foreignkey')
    op.create_foreign_key(None, 'toxico_phase_history', 'toxico_dossiers', ['dossier_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_users_role_id'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'application_roles', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_role_id'), 'users', 'application_roles', ['role_id'], ['role_id'], ondelete='SET NULL')
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'toxico_phase_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_history_dossier'), 'toxico_phase_history', 'toxico_dossiers', ['dossier_id'], ['id'], ondelete='CASCADE')
    op.alter_column('toxico_phase_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'En cours'::character varying"))
    op.drop_constraint(None, 'toxico_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'toxico_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_eval_dossier'), 'toxico_evaluations', 'toxico_dossiers', ['dossier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_eval_creator'), 'toxico_evaluations', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.alter_column('toxico_evaluations', 'phase_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('toxico_evaluations', 'phase_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'toxico_dossiers', type_='foreignkey')
    op.drop_constraint(None, 'toxico_dossiers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_toxico_psychologist'), 'toxico_dossiers', 'users', ['psychologist_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_toxico_patient'), 'toxico_dossiers', 'patients', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_toxico_psy'), 'toxico_dossiers', ['psychologist_id'], unique=False)
    op.create_index(op.f('idx_toxico_active'), 'toxico_dossiers', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('toxico_dossiers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('toxico_dossiers', 'relapse_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'reference_ranges', type_='foreignkey')
    op.create_foreign_key(op.f('reference_ranges_parametre_id_fkey'), 'reference_ranges', 'parametres', ['parametre_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_reference_ranges_parametre'), 'reference_ranges', ['parametre_id'], unique=False)
    op.alter_column('reference_ranges', 'sexe',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.create_table_comment(
        'prescriptions',
        'Prescriptions médicales liées aux dossiers médicaux',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='unique')
    op.create_index(op.f('idx_prescriptions_patient_status'), 'prescriptions', ['patient_id', 'status'], unique=False)
    op.alter_column('prescriptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.create_index(op.f('idx_pharmacy_stock_status'), 'pharmacy', ['stock_status'], unique=False)
    op.create_index(op.f('idx_pharmacy_drug_name_lower'), 'pharmacy', [sa.literal_column('lower(drug_name::text)')], unique=False)
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('idx_patients_toxico'), 'patients', ['is_toxicology'], unique=False, postgresql_where='(is_toxicology = true)')
    op.create_index(op.f('idx_patients_spiritual'), 'patients', ['is_spiritual'], unique=False, postgresql_where='(is_spiritual = true)')
    op.create_index(op.f('idx_patients_name_rev_search'), 'patients', [sa.literal_column("lower((first_name::text || ' '::text) || last_name::text)")], unique=False)
    op.create_index(op.f('idx_patients_global_search'), 'patients', ['code_patient', 'last_name', 'first_name'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_patients_full_name_lower'), 'patients', [sa.literal_column("lower((last_name::text || ' '::text) || first_name::text)")], unique=False)
    op.create_index(op.f('idx_patients_code_search'), 'patients', ['code_patient'], unique=False)
    op.create_index(op.f('idx_patients_clinical'), 'patients', ['is_clinical'], unique=False, postgresql_where='(is_clinical = true)')
    op.create_index(op.f('idx_patients_active'), 'patients', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_constraint(None, 'parametres', type_='foreignkey')
    op.create_foreign_key(op.f('parametres_examen_id_fkey'), 'parametres', 'examens', ['examen_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_parametres_examen'), 'parametres', ['examen_id'], unique=False)
    op.alter_column('parametres', 'input_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'numeric'::character varying"))
    op.drop_constraint(None, 'paiement_echelonne', type_='foreignkey')
    op.drop_constraint(None, 'paiement_echelonne', type_='foreignkey')
    op.create_foreign_key(op.f('fk_paiement_caisse'), 'paiement_echelonne', 'caisse', ['transaction_id'], ['transaction_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('idx_paiement_trans_id'), 'paiement_echelonne', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_organization_config_id'), table_name='organization_config')
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.create_index(op.f('idx_medical_records_patient_date'), 'medical_records', ['patient_id', sa.literal_column('consultation_date DESC')], unique=False)
    op.create_index(op.f('idx_medical_records_motif_code'), 'medical_records', ['motif_code'], unique=False)
    op.create_table_comment(
        'lab_results',
        'Résultats de laboratoire liés aux dossiers médicaux',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'lab_results', type_='unique')
    op.drop_index(op.f('ix_lab_results_batch_id'), table_name='lab_results')
    op.create_index(op.f('idx_lab_results_patient_date'), 'lab_results', ['patient_id', sa.literal_column('test_date DESC')], unique=False)
    op.create_index(op.f('idx_lab_results_batch_id'), 'lab_results', ['batch_id'], unique=False)
    op.create_index(op.f('idx_lab_result_code'), 'lab_results', ['code_lab_patient'], unique=False)
    op.create_index(op.f('idx_code_lab_patient'), 'lab_results', ['code_lab_patient'], unique=False)
    op.alter_column('lab_results', 'batch_id',
               existing_type=sa.UUID(),
               comment='Identifiant unique de lot (UUID) pour grouper les examens créés simultanément',
               existing_nullable=True)
    op.alter_column('lab_results', 'external_patient_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('lab_results', 'note',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('lab_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'lab_result_details', type_='foreignkey')
    op.drop_constraint(None, 'lab_result_details', type_='foreignkey')
    op.create_foreign_key(op.f('lab_result_details_result_id_fkey'), 'lab_result_details', 'lab_results', ['result_id'], ['result_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lab_result_details_parametre_id_fkey'), 'lab_result_details', 'parametres', ['parametre_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_lab_details_parametre'), 'lab_result_details', ['parametre_id'], unique=False)
    op.alter_column('lab_result_details', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'consultation_spirituel', type_='foreignkey')
    op.create_foreign_key(op.f('consultation_spirituel_mp_type_fkey'), 'consultation_spirituel', 'prayer_book_type', ['mp_type'], ['type_code'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('consultation_spirituel', 'psaume',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'mp_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'presc_med_spirituel',
               existing_type=sa.ARRAY(sa.String(length=10)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'presc_generic',
               existing_type=sa.ARRAY(sa.String(length=20)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('consultation_spirituel', 'created_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('consultation_spirituel', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('consultation_spirituel', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_caisse_retrait_category'), 'caisse_retrait', ['category'], unique=False)
    op.drop_constraint(None, 'caisse_item', type_='foreignkey')
    op.create_foreign_key(op.f('caisse_item_transaction_fkey'), 'caisse_item', 'caisse', ['transaction_id'], ['transaction_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('idx_caisse_status'), 'caisse', ['status'], unique=False)
    op.create_index(op.f('idx_caisse_payment_method'), 'caisse', ['payment_method'], unique=False)
    op.drop_index(op.f('ix_audit_user_actions_action_id'), table_name='audit_user_actions')
    op.drop_index(op.f('ix_audit_access_access_id'), table_name='audit_access')
    op.drop_constraint(None, 'appointments', type_='unique')
    op.create_index(op.f('idx_appointments_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_table('audit_user_actions_old',
    sa.Column('action_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('action_id', name=op.f('audit_user_actions_pkey'))
    )
    op.create_table('admin',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('access_level >= 1 AND access_level <= 10', name=op.f('admin_access_level_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('admin_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('admin_pkey'))
    )
    op.create_table('lab_results_audit',
    sa.Column('audit_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lab_results.result_id'], name=op.f('lab_results_audit_result_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('lab_results_audit_pkey'))
    )
    op.create_table('nurse',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('nurse_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('nurse_pkey'))
    )
    op.create_table('audit_access_old',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_access_pkey'))
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('procedure_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description_procedure', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('permissions_pkey'))
    )
    op.create_table('motif_translations',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('label_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('motif_translations_pkey'))
    )
    op.create_table('spiritual_sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('conductor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('spiritual_sessions_pkey'))
    )
    op.create_table('doctor',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('years_experience', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('years_experience >= 0', name=op.f('doctor_years_experience_check')),
    sa.ForeignKeyConstraint(['specialty_id'], ['medical_specialties.specialty_id'], name=op.f('doctor_specialty_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('doctor_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('doctor_pkey'))
    )
    op.create_table('admissions',
    sa.Column('admission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admission_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('discharge_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('current_phase', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('notes_admission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('current_phase >= 1 AND current_phase <= 4', name=op.f('admissions_current_phase_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('admissions_created_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name=op.f('admissions_patient_id_fkey')),
    sa.PrimaryKeyConstraint('admission_id', name=op.f('admissions_pkey'))
    )
    op.create_index(op.f('idx_admissions_active'), 'admissions', ['status'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.create_table('spiritual_attendance',
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PRESENT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.admission_id'], name=op.f('fk_att_admission')),
    sa.ForeignKeyConstraint(['session_id'], ['spiritual_sessions.session_id'], name=op.f('fk_att_session')),
    sa.PrimaryKeyConstraint('session_id', 'admission_id', name=op.f('spiritual_attendance_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('secretaire',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('office_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone_ext', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fax_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('secretaire_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('secretaire_pkey'))
    )
    op.create_table('psych_evaluations',
    sa.Column('eval_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eval_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phase_at_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('mood_score >= 1 AND mood_score <= 10', name=op.f('psych_evaluations_mood_score_check')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.admission_id'], name=op.f('psych_evaluations_admission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], name=op.f('psych_evaluations_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('eval_id', name=op.f('psych_evaluations_pkey'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['application_roles.role_id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('laborantin',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lab_section', sa.VARCHAR(length=100), server_default=sa.text("'général'::character varying"), autoincrement=False, nullable=False),
    sa.Column('certification_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('equipment_access', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('laborantin_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('laborantin_pkey'))
    )
    op.create_table('patient_contacts',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name=op.f('fk_contact_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('patient_contacts_pkey'))
    )
    # ### end Alembic commands ###
